### ISSUE TITLE
I think you need to call req.destroySession on the logout route

### ISSUE THREAD

**Issue by slidenerd** [UnlimitedBytes/nuxt-auth-example#1]
https://github.com/UnlimitedBytes/nuxt-auth-example/blob/master/serverMiddleware/api/v1/resources/sessions.js
In this file, you have called req.logout but I think you also need to call req.destroySession in addition 
https://stackoverflow.com/questions/5573256/how-to-end-a-session-in-expressjs
Thank you for putting this together though

**Comment by UnlimitedBytes** [comment]
I think this will do nothing because the session is directly recreated due to the `saveUninitialized: true,` option in the express-session initialization. Nevertheless, I can understand your point, especially in Europe with the Cookie Policy it would be better to just create the session when it's needed and destroy it after it's no longer needed. 

Although I think I will let this decision to the programmer using the example because in some cases it can be handy to bind data to the user regardless if he is logged in or not and `req.session.destroy()` terminates the entire session not only the login which is what this repo is an example for.
